name: story_view_updated
description: Display stories just like Whatsapp & Instagram. Can be used inline/inside ListView or Column just like Google News app. Comes with gestures to pause, forward & go to previous page.
version: 1.0.0
homepage: https://github.com/printjt/story_view

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  rxdart: ^0.27.7
  video_player: ^2.9.3
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: